/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package enfermedades;

import Conexion.Conexion;
import interfaces.Implementacion;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Edward
 */
public class Eliminar extends javax.swing.JFrame {

    /**
     * Creates new form Eliminar
     */
    Conexion conexion = Conexion.getInstance();
    public Eliminar() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
        this.setTitle("Eliminacion de registros");
        /*botonAtras.setIcon(setIcono("/images/imgBotonAtras2.png",botonAtras));*/

    }
    
    private void limpiar(){
        cajaTexto_AnioEliminar.setText("");
        cajaTexto_CasosEliminar.setText("");
        cajaTexto_NombreEliminar.setText("");
        cajaTexto_CodigoEliminar.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cajaTexto_NombreEliminar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cajaTexto_CasosEliminar = new javax.swing.JTextField();
        botonEliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cajaTexto_AnioEliminar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cajaTexto_CodigoEliminar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        botonBuscarEliminar = new javax.swing.JButton();
        botonAtras = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        cajaTexto_NombreEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cajaTexto_NombreEliminar.setCaretColor(new java.awt.Color(255, 255, 255));
        cajaTexto_NombreEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajaTexto_NombreEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTexto_NombreEliminarActionPerformed(evt);
            }
        });
        cajaTexto_NombreEliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cajaTexto_NombreEliminarKeyReleased(evt);
            }
        });
        getContentPane().add(cajaTexto_NombreEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 217, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Año:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 50, -1));

        cajaTexto_CasosEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cajaTexto_CasosEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTexto_CasosEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(cajaTexto_CasosEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 217, -1));

        botonEliminar.setBackground(new java.awt.Color(0, 102, 204));
        botonEliminar.setFont(new java.awt.Font("Forte", 0, 18)); // NOI18N
        botonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminar.setText("Eliminar");
        botonEliminar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 100, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Casos:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, 20));

        cajaTexto_AnioEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cajaTexto_AnioEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTexto_AnioEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(cajaTexto_AnioEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 217, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Codigo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 50, -1));

        cajaTexto_CodigoEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cajaTexto_CodigoEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTexto_CodigoEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(cajaTexto_CodigoEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 220, -1));

        jLabel5.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Eliminacion de registros");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 270, 40));

        botonBuscarEliminar.setBackground(new java.awt.Color(0, 102, 255));
        botonBuscarEliminar.setFont(new java.awt.Font("Forte", 0, 18)); // NOI18N
        botonBuscarEliminar.setForeground(new java.awt.Color(255, 255, 255));
        botonBuscarEliminar.setText("Buscar");
        botonBuscarEliminar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonBuscarEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(botonBuscarEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 90, 30));

        botonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgBotonAtras.png"))); // NOI18N
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(botonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo4.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cajaTexto_NombreEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTexto_NombreEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaTexto_NombreEliminarActionPerformed

    private void cajaTexto_NombreEliminarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaTexto_NombreEliminarKeyReleased

    }//GEN-LAST:event_cajaTexto_NombreEliminarKeyReleased

    private void cajaTexto_CasosEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTexto_CasosEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaTexto_CasosEliminarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        Implementacion enfermedad_dao= new Implementacion();
        Enfermedad enfermedad = new Enfermedad();
        if(cajaTexto_CodigoEliminar.getText().equals("")||cajaTexto_AnioEliminar.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Ingrese el codigo del registro a eliminar");
        }else{
            String Codigo =cajaTexto_CodigoEliminar.getText();          
            enfermedad.setCodigo(Codigo);
            enfermedad_dao.eliminar(enfermedad);
            limpiar();
            JOptionPane.showMessageDialog(null, "Registro eliminado");
            }
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void cajaTexto_AnioEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTexto_AnioEliminarActionPerformed

    }//GEN-LAST:event_cajaTexto_AnioEliminarActionPerformed

    private void cajaTexto_CodigoEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTexto_CodigoEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaTexto_CodigoEliminarActionPerformed

    private void botonBuscarEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarEliminarActionPerformed
        Implementacion enfermedad_dao= new Implementacion();
        Enfermedad enfermedad = new Enfermedad();
        if(cajaTexto_CodigoEliminar.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Digite el codigo del registro a buscar");
        }else{
            String codigo =cajaTexto_CodigoEliminar.getText();
            enfermedad.setCodigo(codigo);
            enfermedad_dao.buscar(enfermedad);
            cajaTexto_CodigoEliminar.setText(enfermedad.getCodigo());
            cajaTexto_NombreEliminar.setText(enfermedad.getEnfermedad());
            cajaTexto_CasosEliminar.setText(String.valueOf(enfermedad.getCasos()));
            cajaTexto_AnioEliminar.setText(String.valueOf(enfermedad.getAnio()));
            JOptionPane.showMessageDialog(null, "Registro encontrado");
        }
    }//GEN-LAST:event_botonBuscarEliminarActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        this.setVisible(false);
        Menu me = new Menu();
        me.setVisible(true);
    }//GEN-LAST:event_botonAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eliminar().setVisible(true);
            }
        });
    }
    
    public Icon setIcono(String url, JButton boton){
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int ancho=boton.getWidth();
        int alto=boton.getHeight();
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto,Image.SCALE_DEFAULT ));
        return icono;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonBuscarEliminar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JTextField cajaTexto_AnioEliminar;
    private javax.swing.JTextField cajaTexto_CasosEliminar;
    private javax.swing.JTextField cajaTexto_CodigoEliminar;
    private javax.swing.JTextField cajaTexto_NombreEliminar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
