/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package enfermedades;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Edward
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
        this.setTitle("Menu");
        /*botonFrameEliminar.setIcon(setIcono("/images/imgbotonEliminar.png",botonFrameEliminar));*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonFrameRegistros = new javax.swing.JButton();
        botonFrameEstadistica = new javax.swing.JButton();
        botonFrameEliminar = new javax.swing.JButton();
        FondoMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Enfermedades en el Perú");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 260, 40));

        botonFrameRegistros.setBackground(new java.awt.Color(0, 102, 102));
        botonFrameRegistros.setFont(new java.awt.Font("Forte", 0, 18)); // NOI18N
        botonFrameRegistros.setForeground(new java.awt.Color(255, 255, 255));
        botonFrameRegistros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgBotonFrameRegistro.png"))); // NOI18N
        botonFrameRegistros.setText("Registro de enfermedades");
        botonFrameRegistros.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonFrameRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFrameRegistrosActionPerformed(evt);
            }
        });
        getContentPane().add(botonFrameRegistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 280, 50));

        botonFrameEstadistica.setBackground(new java.awt.Color(0, 102, 102));
        botonFrameEstadistica.setFont(new java.awt.Font("Forte", 0, 18)); // NOI18N
        botonFrameEstadistica.setForeground(new java.awt.Color(255, 255, 255));
        botonFrameEstadistica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgBotonFrameEstadistica.png"))); // NOI18N
        botonFrameEstadistica.setText("Estadistica de registros");
        botonFrameEstadistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFrameEstadisticaActionPerformed(evt);
            }
        });
        getContentPane().add(botonFrameEstadistica, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 280, 50));

        botonFrameEliminar.setBackground(new java.awt.Color(0, 102, 102));
        botonFrameEliminar.setFont(new java.awt.Font("Forte", 0, 18)); // NOI18N
        botonFrameEliminar.setForeground(new java.awt.Color(255, 255, 255));
        botonFrameEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgBotonFrameEliminar.png"))); // NOI18N
        botonFrameEliminar.setText("Eliminacion de registros");
        botonFrameEliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonFrameEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFrameEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(botonFrameEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 280, 50));

        FondoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo1.jpg"))); // NOI18N
        getContentPane().add(FondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonFrameEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFrameEliminarActionPerformed
        this.setVisible(false);
        Eliminar e =new Eliminar();
        e.setVisible(true);
    }//GEN-LAST:event_botonFrameEliminarActionPerformed

    private void botonFrameRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFrameRegistrosActionPerformed
        this.setVisible(false);
        Registro r =new Registro();
        r.setVisible(true);
    }//GEN-LAST:event_botonFrameRegistrosActionPerformed

    private void botonFrameEstadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFrameEstadisticaActionPerformed
        this.setVisible(false);
        BaseDeDatos b =new BaseDeDatos();
        b.setVisible(true);
    }//GEN-LAST:event_botonFrameEstadisticaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    
    public Icon setIcono(String url, JButton boton){
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int ancho=boton.getWidth();
        int alto=boton.getHeight();
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto,Image.SCALE_DEFAULT ));
        return icono;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoMenu;
    private javax.swing.JButton botonFrameEliminar;
    private javax.swing.JButton botonFrameEstadistica;
    private javax.swing.JButton botonFrameRegistros;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
