/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package enfermedades;


import interfaces.Implementacion;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;


/**
 *
 * @author Edward
 */
public class Registro extends javax.swing.JFrame {
       /**
     * Creates new form Diseño
     */

    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
        this.setTitle("Registros a BD");
    }

    private void limpiar(){
        cajaTexto_Anio.setText("");
        cajaTexto_Casos.setText("");
        cajaTexto_Nombre.setText("");
        cajaTexto_Codigo.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cajaTexto_Nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cajaTexto_Casos = new javax.swing.JTextField();
        botonRegistrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cajaTexto_Anio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cajaTexto_Codigo = new javax.swing.JTextField();
        botonAtras = new javax.swing.JButton();
        LabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de enfermedades");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 270, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        cajaTexto_Nombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cajaTexto_Nombre.setCaretColor(new java.awt.Color(255, 255, 255));
        cajaTexto_Nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajaTexto_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTexto_NombreActionPerformed(evt);
            }
        });
        cajaTexto_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cajaTexto_NombreKeyReleased(evt);
            }
        });
        getContentPane().add(cajaTexto_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 220, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Año:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 50, -1));

        cajaTexto_Casos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cajaTexto_Casos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTexto_CasosActionPerformed(evt);
            }
        });
        getContentPane().add(cajaTexto_Casos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 220, 20));

        botonRegistrar.setBackground(new java.awt.Color(0, 102, 204));
        botonRegistrar.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        botonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistrar.setText("Registrar");
        botonRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 120, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Casos:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 20));

        cajaTexto_Anio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cajaTexto_Anio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTexto_AnioActionPerformed(evt);
            }
        });
        getContentPane().add(cajaTexto_Anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 220, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Codigo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 50, -1));

        cajaTexto_Codigo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cajaTexto_Codigo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajaTexto_Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTexto_CodigoActionPerformed(evt);
            }
        });
        getContentPane().add(cajaTexto_Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 220, 20));

        botonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgBotonAtras.png"))); // NOI18N
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(botonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        LabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo4.jpg"))); // NOI18N
        LabelFondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(LabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cajaTexto_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTexto_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaTexto_NombreActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        Implementacion enfermedad_dao= new Implementacion();
        Enfermedad enfermedad = new Enfermedad();
        if(cajaTexto_Nombre.getText().equals("")||cajaTexto_Casos.getText().equals("")||cajaTexto_Anio.getText().equals("")||cajaTexto_Codigo.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Ingrese el codigo, nombre, año y numero de casos de la enfermedad");
        }else{
            String codigo = cajaTexto_Codigo.getText();
            String nombre =cajaTexto_Nombre.getText();    
            int casos = Integer.parseInt(cajaTexto_Casos.getText());
            int anio = Integer.parseInt(cajaTexto_Anio.getText());
            enfermedad.setCasos(casos);
            enfermedad.setAnio(anio);
            enfermedad.setEnfermedad(nombre);
            enfermedad.setCodigo(codigo);
            enfermedad_dao.registrar(enfermedad);
            JOptionPane.showMessageDialog(null, "Registro exitoso");
            limpiar();
            }
    }//GEN-LAST:event_botonRegistrarActionPerformed

    
    private void cajaTexto_AnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTexto_AnioActionPerformed
       
    }//GEN-LAST:event_cajaTexto_AnioActionPerformed

    private void cajaTexto_CasosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTexto_CasosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaTexto_CasosActionPerformed

    private void cajaTexto_NombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaTexto_NombreKeyReleased
    
    }//GEN-LAST:event_cajaTexto_NombreKeyReleased

    private void cajaTexto_CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTexto_CodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaTexto_CodigoActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        this.setVisible(false);
        Menu me = new Menu();
        me.setVisible(true);
    }//GEN-LAST:event_botonAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
        
    }
    
    public Icon setIcono(String url, JButton boton){
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int ancho=boton.getWidth();
        int alto=boton.getHeight();
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto,Image.SCALE_DEFAULT ));
        return icono;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelFondo;
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JTextField cajaTexto_Anio;
    private javax.swing.JTextField cajaTexto_Casos;
    private javax.swing.JTextField cajaTexto_Codigo;
    private javax.swing.JTextField cajaTexto_Nombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
